### ISSUE TITLE
RHV Hypervisors not running

### ISSUE THREAD

**Issue by mperezco** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#1]
RHV Hypervisors not running due to the configuration of the CPU type in Cluster.
In App the CPU cluster is configured as AMD Opteron G2 and runs well however, when instantiated, the cluster requires Intel Nehalem CPU configured to be able to run.

Environment configured to use Intel Nehalem CPUs.
Is there a way to have a preselected CPU tipe?

**Comment by bthurber** [comment]
Hi Miguel.  When I inherited the application RHV was already configured to use the Opteron CPU type.  There is no real need to change it for the migration environment to work.  In the past we had to use Opteron for the nested virt to work however I believe Ravello supports the Intel microcode for RHV now.

**Comment by mperezco** [comment]
Brett, 
I spawned a new environment and cluster was down because of this. 
When I tried reconfiguring it in Application, it made the cluster fail.

**Comment by bthurber** [comment]
Why are you changing it?

**Comment by mperezco** [comment]
Because the cluster was down

**Comment by bthurber** [comment]
Hmmmm....this hasn't been an issue in the past.  Need to have guidance from @rut31337

**Comment by rut31337** [comment]
With the new Bare Metal we have to use Nahalem type cpu and we have to revert back to the RHEL provided /usr/share/libvirt/cpu_map.xml.  That will solve the problem.

**Comment by rut31337** [comment]
BTW if you modified the cpu_map.xml on openstack you should revert as well.  And make sure nova.conf is using KVM and not QEMU in its settings.

**Comment by mperezco** [comment]
Not using OSP yet, but I'll take it into account. Thanks!

**Comment by mperezco** [comment]
Fixed.
