### ISSUE TITLE
Provider already tagged

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#23]
Chapter "Configure Red Hat Virtualization as a Migration Destination" asks the user to check the tags for the provider - in my lab, the tags were already applied.

If that is intentional, I recommend to rephrase the guide to say "check the tags" instead of "select the tags"

I comment why those tags are needed would be nice as well. Why do we need to tag the RHV provider with POA "RHV" - CF already knows the provider type anyways?

**Comment by cbolz** [comment]
The tags on the VMware provider were also already applied. Again, if that's expected, I recommend to rephrase to "check tags"...

**Comment by mperezco** [comment]
Tags removed. :-)
Bump v 0.17
