### ISSUE TITLE
Automate.log output in the Web UI

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#24]
Chapter 3.1 recommends to monitor automation.log, but doesn't say how:
either SSH into the appliance then
$ vmdb
$ less log/autiomation.log
OR navigate to Automation, Automate, Log in the Web UI

**Comment by cbolz** [comment]
several chapters ask for checking the automate.log, e.g chapter 3.4 Start VM Pre-Migration, but there is no information what the user should look for. It might be helpful to give a bit more clues.

**Comment by mperezco** [comment]
Good point. Adding reminders of it in the doc as it is only explained in 2.4

**Comment by mperezco** [comment]
Added!.
