### ISSUE TITLE
Pre-Migrate tasks

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#25]
Chapter 3.4 says we have to run "Pre-Migration" of the db VM, but it doesn't explain what's happening.

During the JBoss Migration, this step doesn't appear.

It would be nice to have some background what the steps are doing and why it's not necessary for JBoss

**Comment by cbolz** [comment]
further testing revealed that the pre-migrate task is mandatory, or the actual migrate will fail with the following error: "jboss1: check_premigrate_tag failed: VM jboss1 is not tagged with successful_premigration = true"

**Comment by mperezco** [comment]
Added pre-migration instructions.

**Comment by mperezco** [comment]
Added explanation to pre-migration.
