### ISSUE TITLE
Misspelled work https://vcenter-38a5.rhpds.opentlc.com:9443/vsphere-client/

### ISSUE THREAD

**Issue by dcostakos** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#34]
Misspelled word "Overview" in section 4.3 - subsection 1
"Compute → Migration → Ovewrview."

**Comment by dcostakos** [comment]
In this file : https://github.com/RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration/blob/master/docs/00-redhat_solutions-insfrastructure_migration_v2-lab.adoc#create-an-infrastructure-mapping

**Comment by dcostakos** [comment]
Created pull request 35

**Comment by mperezco** [comment]
Merged. Thanks a lot!
