### ISSUE TITLE
Deployment Lab should specify where to run the commands

### ISSUE THREAD

**Issue by dsorrentino** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#37]
In section 4.1 before it shows the cd and undeploy.yml execution, explicitly state it should be run on the workstation VM.

**Comment by mperezco** [comment]
Added to the doc 
https://github.com/RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration/commit/32838f994047f61d1cbff842111e37ea453d67a9
