### ISSUE TITLE
In section 4.2, the inventory file is called "inventory.example.yml" not "inventory_example.yml"

### ISSUE THREAD

**Issue by my0373** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#39]
In section 4.2, the inventory file is called "inventory.example.yml" not "inventory_example.yml"

The affected line is
"The file inventory_example.yml is created, in the v2v-transformation_host-ansible folder, with the following content:"

**Comment by mperezco** [comment]
Fixed: https://github.com/RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration/commit/06253ad850e12de54d4abb063e9776bb92a3746c

**Comment by mperezco** [comment]
Thanks!
