### ISSUE TITLE
Add link to documentation in RHPDS

### ISSUE THREAD

**Issue by mperezco** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#4]
Add link to documentation in:
a) The long description in RHPDS
b) in the e-mail that gets sent once you request the environment

The link to the documentation:
https://github.com/RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration/blob/master/docs/00-redhat_solutions-insfrastructure_migration_lab.adoc

**Comment by rut31337** [comment]
Done
