### ISSUE TITLE
Add a link to RH318 Training

### ISSUE THREAD

**Issue by cbolz** [RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration#49]
I recommend to add a link to the online training Virtualization and Infrastructure Migration Technical Overview (RH018)

**Comment by mperezco** [comment]
https://github.com/RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration/commit/649e75d87e8f145d48455f3a2e453393131b4f4a

**Comment by mperezco** [comment]
https://github.com/RedHatDemos/RHS-Optimize_IT-Infrastructure_Migration/commit/2b81a9b37a4fbc5d14b84fd8502c1696aeed64a6

**Comment by mperezco** [comment]
Added. Thanks for the idea, I really like it.
